# Hadoop Spark cluster.

version: "3"

networks:
  net_cluster:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - ./volumes/hdfs/namenode:/hadoop/dfs/name
      - ./volumes/bank:/data
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./.env
    ports:
      - "50070:50070"
    networks:
      net_cluster:
        ipv4_address: 172.27.1.5

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - ./volumes/hdfs/datanode:/hadoop/dfs/data
      - ./volumes/bank:/data
    env_file:
      - ./.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    depends_on:
      - namenode
    ports:
      - "50075:50075"
    networks:
      net_cluster:
        ipv4_address: 172.27.1.6

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:8020 namenode:50070 datanode:50075"
    env_file:
      - ./.env
    depends_on:
      - namenode
      - datanode
    networks:
      net_cluster:
        ipv4_address: 172.27.1.15

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    env_file:
      - ./.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore
    networks:
      net_cluster:
        ipv4_address: 172.27.1.7

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    depends_on:
      - hive-metastore-postgresql
    networks:
      net_cluster:
        ipv4_address: 172.27.1.8

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    depends_on:
      - datanode
    networks:
      net_cluster:
        ipv4_address: 172.27.1.9

  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    env_file:
      - ./.env
    volumes:
      - ./hive-site.xml:/spark/conf/hive-site.xml
    networks:
      net_cluster:
        ipv4_address: 172.27.1.10

  spark-worker:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore/metastore
    ports:
      - 8081:8081
    env_file:
      - ./.env
    networks:
      net_cluster:
        ipv4_address: 172.27.1.11

  zeppelin:
    image: apache/zeppelin:0.10.0
    container_name: zeppelin
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_MASTER_URL=spark://spark-master:7077
      - MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - ZEPPELIN_PORT=8080
      - ZEPPELIN_VERSION=0.10.0
    ports:
      - 19090:8080
    depends_on:
      - spark-master
      - namenode
    networks:
      net_cluster:
        ipv4_address: 172.27.1.12

  hue:
    image: gethue/hue:20191107-135001
    hostname: hue
    container_name: hue
    dns: 8.8.8.8
    ports:
      - "8888:8888"
    volumes:
      - ./hue.ini:/usr/share/hue/desktop/conf/hue.ini
      - ./volumes:/volumes
    depends_on:
      - database
      - namenode
      - datanode
      - resourcemanager
    networks:
      net_cluster:
        ipv4_address: 172.27.1.13

  database:
    image: mysql:5.7
    container_name: database
    ports:
      - "33061:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hue
      MYSQL_PASSWORD: secret
    networks:
      net_cluster:
        ipv4_address: 172.27.1.14
