version: "3.8"

services:
  course_postgres:
    container_name: postgres
    build: ./postgres/
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./files:/files
      - ./spaces:/spaces
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
  course_mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/mongo:/data/db
      - ./files:/files
    ports:
      - 27017:27017
    restart: unless-stopped
  course_cassandra:
    image: cassandra:4
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: unless-stopped
    volumes:
      - ./data/cassandra:/var/lib/cassandra
      - ./files:/files
